# Generated by Django 2.2 on 2020-07-03 15:09

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200603_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
